#--- APPLICATION ---#
spring.application.name=payment-webhook-service

#--- DATASOURCE ---#
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_webhook}
spring.datasource.username=${DB_USERNAME:payment_webhook}
spring.datasource.password=${DB_PASSWORD:payment_webhook}

#--- JPA ---#
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
