#--- APPLICATION ---#
spring.application.name=payment-webhook-service

#--- DATASOURCE ---#
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_webhook}
spring.datasource.username=${DB_USERNAME:payment_webhook}
spring.datasource.password=${DB_PASSWORD:payment_webhook}

#--- JPA ---#
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#--- ACMEPAY WEBHOOK ---#
acmepay.webhook.secret=${ACMEPAY_WEBHOOK_SECRET:local-dev-secret}
acmepay.webhook.signature-tolerance=5m
acmepay.webhook.max-body-bytes=16KB
